spring:
  profiles:
    include:
      - core
  main:
    allow-bean-definition-overriding: true
    web-application-type: NONE
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
    initialize-schema: never


---

# local
spring:
  profiles:
    active: local
  batch:
    job:
      enabled: false

---

# develop
spring:
  profiles: develop

---

# release
spring:
  profiles: release