spring:
  profiles:
    include:
      - core
  main:
    allow-bean-definition-overriding: true
    web-application-type: NONE
  batch:
    job:
      enabled: false

---

# local
spring:
  profiles:
    active: local

---

# develop
spring:
  profiles: develop

---

# release
spring:
  profiles: release